### ISSUE TITLE
Bug: verifying merchant screen

### ISSUE THREAD

**Issue by AkashShrestha31** [ayyshim/esewa_pnp#14]
I am getting only verifying merchant screen.

**Comment by ayyshim** [comment]
This problem is not related to **esewa_pnp** itself but esewa's sdk. I will soon contact and raise this issue to them.

**Comment by AkashShrestha31** [comment]
do using native code solve problem or esews skd is running issue?

**Comment by ayyshim** [comment]
Esewa SDK is running issue.

**Comment by AkashShrestha31** [comment]
how can i contact to them for these issue?

**Comment by ayyshim** [comment]
I am contacting them. Don't worry, it will be fixed soon and if there is anything wrong with plugin itself, I will fix it as well.

**Comment by AkashShrestha31** [comment]
ok bro thanks. hope i will get positive response very soon.

**Comment by ayyshim** [comment]
I think it's fixed now. Example project is working fine with esewa_pnp and doesn't stuck in verifying merchant screen anymore. Please test it out once and close this issue if it works for you (also give this repo a star if you think this plugin is good), else you can connect with me via messenger by clicking [this link](https://m.me/ayyshim) and I will provide you further assistance .

**Comment by AkashShrestha31** [comment]
Genius bro. Great. Thanks for your response.

**Comment by AkashShrestha31** [comment]
I was fixed but again same error. Are you connecting them? when they are going to fix this error.?

**Comment by ayyshim** [comment]
I contacted them but they are not responding to my mails. Wait and hope they will fix it soon.

**Comment by AkashShrestha31** [comment]
This error is only in the test environment.  In Live environment everything is working fine. so i am closing this issue.

**Comment by pratima-sapkota** [comment]
I am facing the same issue. When i click on ESewaPaymentButton, verifying merchant screen appears for a short range of time and the app freezes. How to solve this?

**Comment by ayyshim** [comment]
@pratima-sapkota  This is an issue in the eSewa's end and there is nothing much I can do about it. Usually, this gets fixed itself. Just wait for a while.

**Comment by maheshbhattaraai** [comment]
Does this issue still exist @ayyshim in the test enviornement?

**Comment by maheshbhattaraai** [comment]
```
I/ESEWASDK(20624):  URL TO CONNECT FOR CLIENT AUTHENTICATIONhttps://uat.esewa.com.np/mobile/merchant
I/ESEWASDK(20624):  URL TO CONNECT FOR CLIENT AUTHENTICATIONtest
I/ESEWASDK(20624): environment:::: test
I/DpmTcmClient(20624): RegisterTcmMonitor from: $Proxy0
I/ESEWASDK(20624): Login API:::: https://uat.esewa.com.np/mobile/merchant
I/ESEWASDK(20624): Headers:::: {content-type=[application/json], merchantId=[LzFVNSMiXwQ9VSYUPjUbLS8OJDgnECArLjASIDQ0IiMxKhIdKhQkNSk3XyE6DQQwNiNDOQ==], merchantSecret=[JxsSPjYiOiQ9DTo8JBk6JyABKBAkECcrLQ0aKjESNioxDCQhICJYSg==], platform=[Android, Xiaomi Mi A2 Lite]}
I/ESEWASDK(20624): Request Body:::: {"environment":"ERYWAw=="}
W/System.err(20624): javax.net.ssl.SSLException: Read error: ssl=0x78a8e36688: I/O error during system call, Connection reset by peer
```
**Log About Error**
