### ISSUE TITLE
Bug: Execution failed for task ':esewa_pnp:bundleDebugAar'.

### ISSUE THREAD

**Issue by Abhishek-Khanal** [ayyshim/esewa_pnp#15]
**Describe the bug**
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :esewa_pnp project caused this error: C:\flutter\.pub-cache\hosted\pub.dartlang.org\esewa_pnp-1.0.4\android\libs\eSewaSdk.aar

**To Reproduce**
1. Using distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
classpath 'com.android.tools.build:gradle:4.1.2'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

**Environment (please complete the following information):**
 - esewa_pnp Version ^1.0.4
 - Targeted OS: [e.g. iOS, Android]
 - Flutter Version 1.22.6 
 - [only if targetd OS is iOS] Xcode Version and Swift Version

**Comment by ayyshim** [comment]
Try with https://services.gradle.org/distributions/gradle-5.6.2-all.zip once and `classpath 'com.android.tools.build:gradle:3.5.0'`

**Comment by Abhishek-Khanal** [comment]
@ayyshim It works but stuck on verifing merchant screen

**Comment by ayyshim** [comment]
Getting stuck on verifying merchant screen is not an issue related to plugin but eSewa's SDK itself. I suggest you to look #14  and wait while eSewa works on fixing that error.  And also I am closing this issue because your main issue has been resolved. 

Ps: It would be great if you could give this repo a star 😊

**Comment by Abhishek-Khanal** [comment]
Try to make the package work in the newer gradle versions as well.

**Comment by prasid444** [comment]
@ayyshim  won't it work for gradle-6.1.1?

**Comment by ayyshim** [comment]
@prasid444 I haven't tested with 6.x.x gradle yet. If it does not work then I will make sure it will be fixed in new update.

**Comment by prasid444** [comment]
@ayyshim its not working, can you please have a looks.

**Comment by prasid444** [comment]
@ayyshim any  update regarding on issue for distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip ??

**Comment by ayyshim** [comment]
@prasid444 I have recently added and been using esewa_pnp 1.0.4 in my new flutter project and it's working fine with `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` and `classpath 'com.android.tools.build:gradle:3.5.0'`.
It didn't prompt me with any sorts of error.

**Comment by prasid444** [comment]
@ayyshim thanks, it looks like it is not working for 6.1.1... , I updated it with 6.7-all and it's working now. Cheeers 🍸
