### ISSUE TITLE
Build failed with an exception after adding esewa_pnp: ^1.0.4 in dependency

### ISSUE THREAD

**Issue by TAMU73** [ayyshim/esewa_pnp#19]
After I add esewa_pnp: ^1.0.4 in dependency the application cannot run because of some Gradle error.
What is the solution for this?
![image](https://user-images.githubusercontent.com/47109205/111991916-efa81200-8b3c-11eb-9f6d-f637b34cd6da.png)

**Comment by Abhishek-Khanal** [comment]
Try with https://services.gradle.org/distributions/gradle-5.6.2-all.zip once and classpath 'com.android.tools.build:gradle:3.5.0'

**Comment by TAMU73** [comment]
I cannot downgrade the Gradle version which is classpath 'com.android.tools.build:gradle:3.5.0' since I am using the firebase plugin. Any other solution?

**Comment by TAMU73** [comment]
This was the error I got after updating the Gradle versions you mentioned.
![image](https://user-images.githubusercontent.com/47109205/112117338-60a20500-8be3-11eb-83e5-32bd5199750c.png)

**Comment by ayyshim** [comment]
Try this out once https://github.com/ayyshim/esewa_pnp/issues/15#issuecomment-812961416

**Comment by ayyshim** [comment]
This issue is solved in https://github.com/ayyshim/esewa_pnp/issues/15#issuecomment-812961416 so I am closing this issue as well. Please go through that issue comment.
