### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ParasRai2** [ayyshim/esewa_pnp#20]
**Describe the bug**
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :esewa_pnp project caused this error: /Users/username/.pub-cache/hosted/pub.dartlang.org/esewa_pnp-1.0.4/android/libs/eSewaSdk.aar

**To Reproduce**
-Compilation of flutter debug

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - esewa_pnp 1.0.4
 - Targeted OS: Android
 - Flutter 2.0.5

**Additional context**

**Comment by ayyshim** [comment]
Duplicate of #15 

Please go through this https://github.com/ayyshim/esewa_pnp/issues/15#issuecomment-812961416 issue comment. This issue has been already resolved.

**Comment by ParasRai2** [comment]
@ayyshim Thanks, I need to change my app/build.gradle file with
        classpath 'com.android.tools.build:gradle:4.1.0'
        to
        classpath 'com.android.tools.build:gradle:3.5.0'
