### ISSUE TITLE
Bug: App doesnot build with error "Direct local .aar file dependencies are not supported when building an AAR."

### ISSUE THREAD

**Issue by sarinkarma** [ayyshim/esewa_pnp#21]
After installing the package i get this error while trying to build the app.

Execution failed for task ':esewa_pnp:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :esewa_pnp project caused this error: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\esewa_pnp-1.0.4\android\libs\eSewaSdk.aar

Am i missing something while installing?

**Comment by ayyshim** [comment]
This issue has already been solved in issue #15 . Please go through it once.
