### ISSUE TITLE
i cannot run my app after installing esewa pnp 1.0.7

### ISSUE THREAD

**Issue by Kashish-Manandhar** [ayyshim/esewa_pnp#28]
Execution failed for task ':esewa_pnp:bundleDebugAar'. > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :esewa_pnp project caused this error: C:\Users\User\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\esewa_pnp-1.0.7\android\libs\eSewaSdk.aar

**Comment by mhrjnamar** [comment]
I am also facing the same issue @ayyshim I hope you could check into this as soon as possible

**Comment by ayyshim** [comment]
Please checkout the closed issue  #15  which was solved before and the nature of error was same.

**Comment by Kashish-Manandhar** [comment]
thankyou .... this solved the problem
