### ISSUE TITLE
Bug: module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4 compiler

### ISSUE THREAD

**Issue by mhrjnamar** [ayyshim/esewa_pnp#29]
I had tried to test eSewa SDK in the simulator and got the error while building the project

SwiftEsewaPnpPlugin.swift:3:8: error: module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4 compiler: /Volumes/Storage/Flutter/insurance_flutter_app/ios/.symlinks/plugins/esewa_pnp/ios/EsewaSDK.framework/Modules/EsewaSDK.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import EsewaSDK
           ^

![Screen Shot 2021-06-21 at 11 29 22](https://user-images.githubusercontent.com/17248241/122712638-f5201000-d283-11eb-92be-e2430f280975.png)

**Comment by dhruv048** [comment]
hey @mhrjnamar, i don't know if it is relevant to you but try running on real device, 
i didn't get this issue when i was building in real device, but got the issue as soon as i shifted to simulator.
