### ISSUE TITLE
Bug: Execution failed for task ':esewa_pnp:bundleDebugAar'.

### ISSUE THREAD

**Issue by alensh12** [ayyshim/esewa_pnp#30]
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :esewa_pnp project caused this error:

**Comment by ayyshim** [comment]
This issue has already been raised and solved in issue #15 so I am closing this issue.
