### ISSUE TITLE
Bug: Module compiled with Swift 5.4 cannot be imported by the Swift 5.5 compiler

### ISSUE THREAD

**Issue by yetitechnepal** [ayyshim/esewa_pnp#38]
**Describe the bug**
On compiling for ios, xcode is firing the above bug

**To Reproduce**
xcode version 12 with swift 5.5

**Environment (please complete the following information):**
 - esewa_pnp ^1.07

**Comment by pharidali** [comment]
same problem

**Comment by lancemeup** [comment]
same problem

**Comment by ayyshim** [comment]
I have talked to esewa and they are working on Framework for swift 5.5. I will update this plugin as soon as I get update from esewa.

**Comment by mhrjnamar** [comment]
What should we do for now?

**Comment by ayyshim** [comment]
@mhrjnamar you can try downgrading xcode to 12.x and swift compiler version to 5.4.

**Comment by paraslamsong** [comment]
> @mhrjnamar you can try downgrading xcode to 12.x and swift compiler version to 5.4.

macOS 12 is not allowing to downgrade xCode

**Comment by mhrjnamar** [comment]
@paraslamsong  
I am using webview now.  I think it is  better to use webview

**Comment by paraslamsong** [comment]
> @paraslamsong I am using webview now. I think it is better to use webview

You can use code magic for remote build

**Comment by ayyshim** [comment]
esewa_pnp v.1.1.0 has been shipped with fixes.

Thanks to @awazgyawali for the fix.
