### ISSUE TITLE
Unable to login to esewa through the app. it says "Incorrect username or password"

### ISSUE THREAD

**Issue by dhruv048** [ayyshim/esewa_pnp#4]
Hey again, 
I dont know why but every time i try to log in to esewa through my app, it says "Incorrect username or password" although the credentials are correct. 
i can log in directly to esewa app with those credential but not through my app.
Have you ever faced this error and what causes this.
i have implemented the plugin as directed by you in example tab and your video.
please help me

**Comment by ayyshim** [comment]
You must be trying to login with your real eSewa account in TEST environment. You can only login with your real account in LIVE environment.

**Comment by dhruv048** [comment]
ohh Thanks a lot mate...

**Comment by ayyshim** [comment]
I hope that answered your question so I am closing this issue. Don't forget to give this repository a star 🙂

**Comment by coder-Aayush** [comment]
Hello @ayyshim, 
Since we cannot test payment in a TEST environment, is there any way we can test payment is working or not in TEST Environment.

**Comment by ayyshim** [comment]
> Hello @ayyshim, 
> Since we cannot test payment in a TEST environment, is there any way we can test payment is working or not in TEST Environment.

You can use test account which will only work in test environment with test clientID and secretKey provided by eSewa.

Please process with below details:
Username: 9806800001
password: Nepal@123
