### ISSUE TITLE
Build failed on android: 

### ISSUE THREAD

**Issue by sagarshree** [ayyshim/esewa_pnp#40]
**Describe the bug**

**To Reproduce**
1. Use Gradle version 4.1.3
2. Use Flutter version 2.8
3. Use esewa_pnp 1.1.0

**Expected behavior**
Build fails(both debug and release) with exception:

**Execution failed for task ':esewa_pnp:bundleReleaseAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :esewa_pnp project caused this error: /Users/sagarshree/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/esewa_pnp-1.1.0/android/libs/eSewaSdk.aar**

 - esewa_pnp 1.0.1
 - Targeted OS: [e.g. iOS, Android]
 - Flutter Version 2.8
 - [only if targetd OS is iOS] Xcode Version and Swift Version

**Comment by ayyshim** [comment]
Downgrade your gradle version to 3.5.0

**Comment by sagarshree** [comment]
ok
