### ISSUE TITLE
Bug: Build Failed on Android Direct local .aar file dependencies are not supported when building an AAR. 

### ISSUE THREAD

**Issue by aryalg** [ayyshim/esewa_pnp#44]
**Describe the bug**
Build Failed on Android Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error).

**To Reproduce**
1. Upgrade Flutter Version to 2.10.0

**Expected behavior**
Build should succeed on android

**Environment (please complete the following information):**
 - esewa_pnp: 1.1.0
 - Targeted OS: ANDROID
 - Flutter Version: 2.10.0

**Comment by ayyshim** [comment]
It looks like you have fixed it in your fork. Please open a PR if it's working on your end. @aryalg

**Comment by Roopaish** [comment]
Please merge the PR he made @aryalg [ayyshim](https://github.com/ayyshim)

**Comment by ayyshim** [comment]
PR has been merged and this issue is fixed.
