### ISSUE TITLE
Bug: Module compile error

### ISSUE THREAD

**Issue by dbspoudel** [ayyshim/esewa_pnp#46]
**Describe the bug**
Module compiled with Swift 5.5.1 cannot be imported by the Swift 5.5.2 compiler:

**To Reproduce**
1. Build an app by latest Xcode & swift compiler

**Screenshots**
<img width="642" alt="Screen Shot 2022-02-17 at 8 37 50 PM" src="https://user-images.githubusercontent.com/31642846/154507252-aadd97b9-3c42-48ad-9719-3ec3a7a26489.png">

**Environment:**
 - esewa_pnp 1.1.0
 - Flutter Version 2.10.1
 - Xcode 13.2.1 and Swift 5.5.2

**Comment by ayyshim** [comment]
Please downgrade your xcode version and it should fix it.
