### ISSUE TITLE
Swift Compile issue: Missing argument for parameter 'paymentProperties' in call  sdk?.initiatePayment

### ISSUE THREAD

**Issue by Roopaish** [ayyshim/esewa_pnp#49]
I compiled my app using dev and got this error. It's from this [file](https://github.com/ayyshim/esewa_pnp/blob/dev/ios/Classes/SwiftEsewaPnpPlugin.swift)

`Missing argument for parameter 'paymentProperties' in call `  
```swift
sdk?.initiatePayment(merchantId: clientID, merchantSecret: secretKey, productName: productName, productAmount: amount, productId: productID, callbackUrl: callBackURL )
```

**Comment by pharidali** [comment]
same problem

**Comment by Roopaish** [comment]
@pharidali  it doesn't show up when using with real device.
